name: update-packets
on: push
jobs:
  update-packets-job:
    runs-on: ubuntu-latest
    steps:
      - name: update information about packets
        run: sudo apt-get update
      - name: update packets
        run: sudo apt-get upgrade